// <auto-generated />
using EEWA.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EEWA.DAL.Migrations;

[DbContext(typeof(SandBoxContext))]
partial class SandBoxContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("EEWA.DAL.Model.Component", b =>
            {
                b.Property<int>("ComponentID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComponentID"));

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal?>("InstallationPerUnit")
                    .HasColumnType("decimal(10,2)");

                b.Property<string>("Position")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<decimal?>("Quantity")
                    .HasColumnType("decimal(10,2)");

                b.Property<int?>("SectionID")
                    .HasColumnType("int");

                b.Property<int?>("SortOrder")
                    .HasColumnType("int");

                b.Property<decimal?>("SupplyPerUnit")
                    .HasColumnType("decimal(10,2)");

                b.Property<decimal?>("Total")
                    .HasColumnType("decimal(10,2)");

                b.Property<decimal?>("TotalPerUnit")
                    .HasColumnType("decimal(10,2)");

                b.Property<string>("Unit")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("ComponentID");

                b.ToTable("Component", "dbo");
            });

        modelBuilder.Entity("EEWA.DAL.Model.ProjectSection", b =>
            {
                b.Property<int>("SectionID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionID"));

                b.Property<string>("SectionName")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("SheetName")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<int?>("SortOrder")
                    .HasColumnType("int");

                b.HasKey("SectionID");

                b.ToTable("ProjectSection", "dbo");
            });
#pragma warning restore 612, 618
    }
}
